name: Build and deploy JAR app to Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App
  JAVA_VERSION: '11'                  # set this to the Java version to use
  DISTRIBUTION: zulu                  # set this to the Java distribution

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Show current directory
        run: pwd  # 현재 작업 디렉토리를 출력

      - name: List all files in the workspace before build
        run: ls -alR  # 빌드 전 모든 디렉토리 및 파일을 재귀적으로 나열

      - name: Build with Gradle
        run: ./gradlew clean build --console=plain  # 자세한 로그 출력을 위해 --console=plain 사용

      - name: List build directory
        run: ls -al build/libs/  # 빌드된 파일을 확인

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: 'build/libs/*.jar'

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Show current directory after download
        run: pwd  # 다운로드 후 작업 디렉토리를 출력

      - name: List all files in the workspace after download
        run: ls -alR  # 다운로드 후 모든 디렉토리 및 파일을 재귀적으로 나열

      - name: List build directory after download
        run: ls -al ${{ github.workspace }}/build/libs/  # 다운로드 후 빌드 디렉토리 파일 확인

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
