name: Build and deploy JAR app to Azure Web App - bambam

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # 필요한 경우 Java 버전을 조정하세요.
          distribution: 'temurin'  # 또는 원하는 JDK 배포판을 선택하세요.

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # 이 설정은 JWT 요청을 위한 필수 설정입니다.
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FF14BF4E4334B00B1FE30DD937C527B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F998734AF8714D7AA0CF45E00CA222CE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ABDE11D7251D4C36B514F5641A5C09E4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bambam'
          slot-name: 'Production'
          package: '*.jar'
