name: Build and deploy JAR app to Azure Web App - bambam

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Show current directory
        run: pwd  # 현재 작업 디렉토리를 출력

      - name: List all files in the workspace after build
        run: ls -alR  # 모든 디렉토리 및 파일을 재귀적으로 나열

      - name: List build directory
        run: ls -al build/libs/  # 빌드된 파일 확인

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Show current directory after download
        run: pwd  # 현재 작업 디렉토리를 출력

      - name: List all files in the workspace after download
        run: ls -alR  # 모든 디렉토리 및 파일을 재귀적으로 나열

      # - name: List build directory after download
      #   run: ls -al ${{ github.workspace }}/build/libs/  # 다운로드된 파일 확인

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FF14BF4E4334B00B1FE30DD937C527B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F998734AF8714D7AA0CF45E00CA222CE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ABDE11D7251D4C36B514F5641A5C09E4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bambam'
          slot-name: 'Production'
          package: './bambam_backend-0.0.1-SNAPSHOT.jar'  # 절대 경로 사용
